### ISSUE TITLE
The bot says a channel is already opened when user has received the confirm message before

### ISSUE THREAD

**Issue by AntoineJT** [RedsTom/TicketTools#13]
**Note: this issue considers the bug #10 has already been fixed!**

When you have received the message allowing to open a ticket, the bot considers that a ticket has been opened with you. 
It should just prevent sending a new message when doing a !new

## Steps to reproduce

1. Try to create a new ticket
2. Don't reply to the bot's DM
3. Try again to create a new ticket

**Comment by RedsTom** [comment]
Related to #19
